language: python
python:
  - "2.7"

install:
  - pip install -r requirements-base.txt --use-mirrors
  - pip install -r requirements-dev.txt --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run --source='to_be_a_musician' --omit=*migrations* to_be_a_musician/manage.py test djtinysong common songs
after_script:
  - coveralls
